"""Do M3T's landfill/wastewater method variants produce meaningfully different
SIMULATED ENHANCEMENTS -- not just different totals -- at the actual §14
landfill/WWTP event receptors?

For each of the 3 landfill (GHGRP reported/generation_first/collection_first)
and 8 wastewater (CWNS|DMR x GHGI|Moore x septic national|state) variant
rasters generated by run_m3t_landfill_wwtp_variants.py: regrid onto the
Jacobian's native grid (nearest, same convention as build_m3t_prior.py),
then for each already-identified landfill/WWTP-dominated event (§14/§15;
reusing joint_correlation_sweep.collect_events), compute the predicted
enhancement H_i @ density_variant at that event's elevated receptors under
every variant of its dominant category. The spread across variants, compared
to the event's actual unexplained gap (z - modeled), is the "meaningful or
not" test -- a variant swap that moves the prediction by a fraction of the
gap comparable to or larger than typical would be a real, checkable source
of prior-shape uncertainty; a swap that barely moves it says variant choice
isn't where the uncertainty lives.

No re-solve; reuses cached Jacobian-row-read pattern from
point_source_amplification_check.py / joint_correlation_sweep.py.
"""

from __future__ import annotations

import os
import sys

import numpy as np
import xarray as xr
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, ".")

from adapters.gridded_state import _haversine_km
from adapters.jacobian_operator import JacobianFile
from halo_oe.io_bundle import load_inversion

import joint_correlation_sweep as J

M3T_OUT = "/scratch/scrowel3_lab/halo-nyc/m3t_variant_run/out"
JAC_DIR = "/scratch/scrowel3_lab/halo-nyc/stilt/harvard_jacobians"
NMOL_TO_UMOL = 1e-3

LANDFILL_VARIANTS = ["reported", "generation_first", "collection_first"]
LANDFILL_FILES = {v: f"Landfill_sector_total_GHGRP_{v}.nc" for v in LANDFILL_VARIANTS}

WASTEWATER_VARIANTS = [f"{src}_{meth}_{kind}"
                       for src in ("CWNS", "DMR")
                       for meth in ("GHGI", "Moore")
                       for kind in ("national", "state")]
WASTEWATER_FILES = {v: f"Wastewater_sector_total_{v}.nc" for v in WASTEWATER_VARIANTS}


def read_variant(path, lat, lon):
    """Regrid one M3T output raster onto (lat, lon), nearest, µmol m^-2 s^-1.
    Mirrors build_m3t_prior.py::_read_category."""
    ds = xr.open_dataset(path, decode_coords="all")
    da = ds[next(iter(ds.data_vars))].astype("float64")
    ydim, xdim = da.dims[-2], da.dims[-1]
    da = da.rename({ydim: "y", xdim: "x"}).sortby("y").sortby("x")
    da = da.interp(y=lat, x=lon, method="nearest")
    return np.nan_to_num(da.values, nan=0.0) * NMOL_TO_UMOL


def main():
    inv = load_inversion(J.BUNDLE)
    lat, lon = inv.grid.lat, inv.grid.lon   # Jacobian's own native grid

    print("regridding variant rasters onto the Jacobian grid...")
    landfill_grids = {v: read_variant(os.path.join(M3T_OUT, f), lat, lon)
                       for v, f in LANDFILL_FILES.items()}
    wastewater_grids = {v: read_variant(os.path.join(M3T_OUT, f), lat, lon)
                         for v, f in WASTEWATER_FILES.items()}
    print(f"landfill grids: {list(landfill_grids)}")
    print(f"wastewater grids: {list(wastewater_grids)}")

    # quick spatial-pattern check: correlation between variants, over cells
    # where at least one variant is nonzero
    def pattern_corr(grids):
        names = list(grids)
        any_nz = np.any([g > 0 for g in grids.values()], axis=0)
        flat = {n: grids[n][any_nz] for n in names}
        print(f"    {'':20s} " + " ".join(f"{n:>18s}" for n in names))
        for a in names:
            row = " ".join(f"{np.corrcoef(flat[a], flat[b])[0,1]:>18.4f}" for b in names)
            print(f"    {a:20s} {row}")

    print("\nlandfill variant spatial-pattern correlation (nonzero cells):")
    pattern_corr(landfill_grids)
    print("\nwastewater variant spatial-pattern correlation (nonzero cells):")
    pattern_corr(wastewater_grids)

    events = J.collect_events(inv)
    print(f"\n{len(events)} qualifying landfill/WWTP-dominated events")

    jf_cache, row_cache = {}, {}

    def get_row(fid, ri):
        key = (fid, int(ri))
        if key not in row_cache:
            if fid not in jf_cache:
                jf_cache[fid] = JacobianFile(os.path.join(JAC_DIR, f"{fid}.nc"))
            jf = jf_cache[fid]
            jac = jf._ds.variables[jf._jac_var]
            row_cache[key] = np.asarray(jac[int(ri), :, :]).reshape(-1)
        return row_cache[key]

    results = []
    print(f"\n{'event':>5} {'fid':>14} {'dom_cat':>10} {'n_recept':>8}  "
          f"{'gap_typical':>11}  {'pred_min':>10} {'pred_max':>10} {'pred_range':>10} "
          f"{'range/|gap|':>11}")
    print("-" * 100)
    for ei, ev in enumerate(events):
        variants = landfill_grids if ev["dom_cat"] == "landfill" else wastewater_grids
        gap = ev["z"] - ev["modeled"]
        gap_typical = np.median(np.abs(gap))

        preds = {}
        for vname, grid in variants.items():
            grid_flat = grid.reshape(-1)
            total = 0.0
            for ri in ev["r_raw_idx"]:
                row = get_row(ev["fid"], ri)
                total += row @ grid_flat
            preds[vname] = total / len(ev["r_raw_idx"])   # mean predicted enhancement across event receptors

        pred_vals = np.array(list(preds.values()))
        pred_range = pred_vals.max() - pred_vals.min()
        rel = pred_range / gap_typical if gap_typical > 0 else np.nan
        print(f"{ei:>5} {ev['fid']:>14} {ev['dom_cat']:>10} {len(ev['r_raw_idx']):>8}  "
              f"{gap_typical:>11.4f}  {pred_vals.min():>10.4f} {pred_vals.max():>10.4f} "
              f"{pred_range:>10.4f} {rel:>11.3f}")
        results.append(dict(ei=ei, fid=ev["fid"], dom_cat=ev["dom_cat"], gap_typical=gap_typical,
                             pred_range=pred_range, rel=rel, preds=preds))

    for fc in jf_cache.values():
        fc.close()

    rels = np.array([r["rel"] for r in results if np.isfinite(r["rel"])])
    print(f"\nvariant-induced prediction range, as a fraction of each event's typical "
          f"unexplained gap: median={np.median(rels):.3f}  p75={np.percentile(rels,75):.3f}  "
          f"max={rels.max():.3f}")

    fig, ax = plt.subplots(figsize=(8, 5))
    colors = {"landfill": "tab:blue", "wastewater": "tab:orange"}
    for r in results:
        ax.scatter(r["ei"], r["rel"], color=colors[r["dom_cat"]], s=40)
    ax.axhline(1.0, color="k", ls="--", lw=1, label="range = typical gap")
    ax.set_xlabel("event index")
    ax.set_ylabel("variant-induced prediction range / typical |gap|")
    ax.set_title("How much does M3T method-variant choice move the predicted\n"
                 "enhancement, relative to what's actually unexplained?")
    for cat, c in colors.items():
        ax.scatter([], [], color=c, label=cat)
    ax.legend()
    plt.savefig("runs/m3t_variant_spatial_check.png", bbox_inches="tight", dpi=110)
    plt.close(fig)
    print("plot -> runs/m3t_variant_spatial_check.png")


if __name__ == "__main__":
    main()
